# Generated by Django 6.0.3 on 2026-04-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_cart_products_cart_created_at_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Created_at',
            new_name='created_at',
        ),
    ]
