# Generated by Django 6.0.3 on 2026-04-13 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
